Fix bug when parsing selector schemas
Discovered whilst debugging a different issue. The code below is
showing the wrong error message because a null pointer assignment.

```scss
```
LibSass
```
Error: Invalid CSS after "#": expected "{", was "#{a==b}"
```
Ruby Sass
```
Error: Invalid CSS after "#{a==b}": expected "{", was ""
```
Spec https://github.com/sass/sass-spec/pull/1106